from fastapi import FastAPI, Depends, HTTPException
from fastapi.responses import JSONResponse
from sqlalchemy.orm import Session
from common.database import get_db
from common.models import Session as SessionModel, SessionCheckpoint, Output
from common.config import get_settings
import json
import uuid
import asyncio
import redis
from typing import Dict, Any

app = FastAPI(title="UJU Explainer", version="4.0")
settings = get_settings()
redis_client = redis.from_url(settings.redis_url, decode_responses=True)

def build_plain_english_explanation(session: SessionModel) -> str:
    """Translate technical output to plain English."""
    compressed = session.compressed_signal or {}
    lens_data = session.lens_outputs or {}
    critic_data = session.critic_output or {}
    
    lines = []
    lines.append("# UJU Cycle Analysis Report\n")
    
    # Compressed signal summary
    signal = compressed.get("compressed_signal", "No signal available.")
    lines.append(f"## Summary\n{signal}\n")
    
    # Confidence
    conf_interval = compressed.get("confidence_interval", {})
    lower = conf_interval.get("lower", 0.0)
    upper = conf_interval.get("upper", 1.0)
    lines.append(f"**Confidence Interval:** {lower:.0%} – {upper:.0%}\n")
    
    # Lens insights
    lens_outputs = lens_data.get("lens_outputs", [])
    if lens_outputs:
        lines.append("## Key Insights by Lens\n")
        for lens in lens_outputs:
            name = lens.get("lens_name", lens.get("lens", "Unknown"))
            insights = lens.get("key_insights", [])
            if insights:
                lines.append(f"### {name} Lens")
                for insight in insights[:3]:
                    lines.append(f"- {insight}")
                lines.append("")
    
    # ACH result
    ach = critic_data.get("ach_matrix", {})
    if ach:
        lines.append(f"## Most Likely Hypothesis\n{ach.get('most_likely', 'N/A')}")
        lines.append(f"**Confidence:** {ach.get('confidence', 0):.0%}\n")
    
    # Confounders
    conf = critic_data.get("confounder_analysis", {})
    if conf.get("confounders_detected", 0) > 0:
        lines.append("## ⚠️ Potential Confounders Detected")
        for c in conf.get("potential_confounders", [])[:3]:
            lines.append(f"- {c.get('variable', 'Unknown')}: {c.get('type', '')}")
        lines.append("")
    
    # Design principles (Ostrom)
    cmo = lens_data.get("cmo", {})
    if cmo:
        dps = cmo.get("design_principles", [])
        if dps:
            lines.append("## Ostrom's Design Principles")
            for dp in dps:
                if dp.get("score", 0) > 0.3:
                    lines.append(f"- **{dp['principle']}** (score: {dp['score']:.0%})")
            lines.append("")
    
    # Uncertainty flags
    uncertainty = compressed.get("uncertainty_flags", [])
    if uncertainty:
        lines.append("## Uncertainty Flags")
        for flag in uncertainty:
            lines.append(f"- {flag}")
        lines.append("")
    
    lines.append("\n---\n*Generated by UJU Cycle Live v4.0 — Accelerated Probabilistic Reasoning*")
    return "\n".join(lines)

def build_traceability(session: SessionModel) -> Dict:
    """Build 'Why this answer?' traceability info."""
    return {
        "session_id": str(session.id),
        "user_id": session.user_id,
        "mode": session.mode,
        "status": session.status,
        "created_at": str(session.created_at),
        "completed_at": str(session.completed_at),
        "pipeline_stages": [
            {"stage": "ingest", "completed": True},
            {"stage": "compress", "completed": session.compressed_signal is not None},
            {"stage": "lens_shift", "completed": session.lens_outputs is not None},
            {"stage": "weave", "completed": session.lens_outputs is not None and "krippendorff_alpha" in str(session.lens_outputs)},
            {"stage": "critic", "completed": session.critic_output is not None},
            {"stage": "explain", "completed": True},
        ],
        "methodologies_used": session.compressed_signal.get("methodology_hints", []) if session.compressed_signal else [],
        "lens_count": len(session.lens_outputs.get("lens_outputs", [])) if session.lens_outputs else 0,
    }

def build_json_output(session: SessionModel) -> Dict:
    return {
        "session_id": str(session.id),
        "compressed_signal": session.compressed_signal,
        "lens_outputs": session.lens_outputs,
        "critic_output": session.critic_output,
        "explain": {
            "plain_english": build_plain_english_explanation(session),
            "traceability": build_traceability(session)
        },
        "mode": session.mode,
        "status": session.status
    }

async def process_explain(session_id: str, db: Session):
    session = db.query(SessionModel).filter(SessionModel.id == uuid.UUID(session_id)).first()
    if not session:
        return
    
    explanation = build_plain_english_explanation(session)
    traceability = build_traceability(session)
    json_output = build_json_output(session)
    
    session.explainer_output = {"plain_english": explanation, "traceability": traceability}
    session.status = "completed"
    session.completed_at = session.completed_at or __import__('datetime').datetime.utcnow()
    db.commit()
    
    # Save output in multiple formats
    for fmt in ["json", "markdown"]:
        content = json_output if fmt == "json" else explanation
        out = Output(session_id=session.id, format=fmt, content=content)
        db.add(out)
    db.commit()
    
    cp = SessionCheckpoint(session_id=session.id, stage="explain", state={"status": "complete"})
    db.add(cp)
    db.commit()

async def worker():
    while True:
        try:
            _, job_data = redis_client.brpop("uju:explainer_queue", timeout=5)
            if not job_data:
                await asyncio.sleep(1)
                continue
            job = json.loads(job_data)
            from sqlalchemy import create_engine
            from sqlalchemy.orm import sessionmaker
            engine = create_engine(settings.database_url)
            SessionLocal = sessionmaker(bind=engine)
            db = SessionLocal()
            await process_explain(job["session_id"], db)
            db.close()
        except Exception as e:
            await asyncio.sleep(2)

@app.on_event("startup")
async def startup():
    asyncio.create_task(worker())

@app.get("/health")
async def health():
    return {"status": "healthy", "service": "explainer"}

@app.get("/explain/{session_id}")
async def get_explanation(session_id: str, format: str = "json", db: Session = Depends(get_db)):
    session = db.query(SessionModel).filter(SessionModel.id == uuid.UUID(session_id)).first()
    if not session:
        raise HTTPException(404, "Session not found")
    if format == "markdown":
        return JSONResponse({"markdown": build_plain_english_explanation(session)})
    return build_json_output(session)

@app.get("/trace/{session_id}")
async def get_traceability(session_id: str, db: Session = Depends(get_db)):
    session = db.query(SessionModel).filter(SessionModel.id == uuid.UUID(session_id)).first()
    if not session:
        raise HTTPException(404, "Session not found")
    return build_traceability(session)
